class Client {
  final String? name, adress, city, zipcode, phone, email, description, logo;

  Client(
      {this.adress,
      this.name,
      this.city,
      this.zipcode,
      this.phone,
      this.email,
      this.description,
      this.logo});
}

List clientList = [
  Client(
    adress: "Place Saint-Denis",
    name: "Roussel et Roussel",
    city: "Amiens",
    zipcode: "14754",
    phone: "05 34 57 71 01",
    email: "rh@roussquare.fr",
    description: "Chuck Norris hosting is 101% uptime guaranteed.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Rue Montorgueil",
    name: "Blanchard et Blanchard SCOP",
    city: "Mulhouse",
    zipcode: "98521",
    phone: "+33 261239584",
    email: "rh@clementscop.fr",
    description:
        "All arrays Chuck Norris declares are of infinite size, because Chuck Norris knows no bounds.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Avenue Adolphe Mille",
    name: "Paul GIE",
    city: "Bourges",
    zipcode: "47521",
    phone: "0179129242",
    email: "rh@gie.fr",
    description:
        "Chuck Norris doesn't need the cloud to scale his applications, he uses his laptop.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Impasse de la Ferronnerie",
    name: "Remy et Remy",
    city: "Cholet",
    zipcode: "14896",
    phone: "+33 995603458",
    email: "rh@remy.fr",
    description: "No statement can catch the ChuckNorrisException.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Passage de la Bûcherie",
    name: "Charpentier SEM",
    city: "Clermont-Ferrand",
    zipcode: "88857",
    phone: "0585106609",
    email: "rh@charpentier.fr",
    description:
        "Chuck Norris doesn't need a java compiler, he goes straight to .war",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Place Saint-Denis",
    name: "Roussel et Roussel",
    city: "Amiens",
    zipcode: "14754",
    phone: "05 34 57 71 01",
    email: "rh@roussquare.fr",
    description: "Chuck Norris hosting is 101% uptime guaranteed.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Rue Montorgueil",
    name: "Blanchard et Blanchard SCOP",
    city: "Mulhouse",
    zipcode: "98521",
    phone: "+33 261239584",
    email: "rh@clementscop.fr",
    description:
        "All arrays Chuck Norris declares are of infinite size, because Chuck Norris knows no bounds.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Avenue Adolphe Mille",
    name: "Paul GIE",
    city: "Bourges",
    zipcode: "47521",
    phone: "0179129242",
    email: "rh@gie.fr",
    description:
        "Chuck Norris doesn't need the cloud to scale his applications, he uses his laptop.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Impasse de la Ferronnerie",
    name: "Remy et Remy",
    city: "Cholet",
    zipcode: "14896",
    phone: "+33 995603458",
    email: "rh@remy.fr",
    description: "No statement can catch the ChuckNorrisException.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Passage de la Bûcherie",
    name: "Charpentier SEM",
    city: "Clermont-Ferrand",
    zipcode: "88857",
    phone: "0585106609",
    email: "rh@charpentier.fr",
    description:
        "Chuck Norris doesn't need a java compiler, he goes straight to .war",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Place Saint-Denis",
    name: "Roussel et Roussel",
    city: "Amiens",
    zipcode: "14754",
    phone: "05 34 57 71 01",
    email: "rh@roussquare.fr",
    description: "Chuck Norris hosting is 101% uptime guaranteed.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Rue Montorgueil",
    name: "Blanchard et Blanchard SCOP",
    city: "Mulhouse",
    zipcode: "98521",
    phone: "+33 261239584",
    email: "rh@clementscop.fr",
    description:
        "All arrays Chuck Norris declares are of infinite size, because Chuck Norris knows no bounds.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Avenue Adolphe Mille",
    name: "Paul GIE",
    city: "Bourges",
    zipcode: "47521",
    phone: "0179129242",
    email: "rh@gie.fr",
    description:
        "Chuck Norris doesn't need the cloud to scale his applications, he uses his laptop.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Impasse de la Ferronnerie",
    name: "Remy et Remy",
    city: "Cholet",
    zipcode: "14896",
    phone: "+33 995603458",
    email: "rh@remy.fr",
    description: "No statement can catch the ChuckNorrisException.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Passage de la Bûcherie",
    name: "Charpentier SEM",
    city: "Clermont-Ferrand",
    zipcode: "88857",
    phone: "0585106609",
    email: "rh@charpentier.fr",
    description:
        "Chuck Norris doesn't need a java compiler, he goes straight to .war",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Place Saint-Denis",
    name: "Roussel et Roussel",
    city: "Amiens",
    zipcode: "14754",
    phone: "05 34 57 71 01",
    email: "rh@roussquare.fr",
    description: "Chuck Norris hosting is 101% uptime guaranteed.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Rue Montorgueil",
    name: "Blanchard et Blanchard SCOP",
    city: "Mulhouse",
    zipcode: "98521",
    phone: "+33 261239584",
    email: "rh@clementscop.fr",
    description:
        "All arrays Chuck Norris declares are of infinite size, because Chuck Norris knows no bounds.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Avenue Adolphe Mille",
    name: "Paul GIE",
    city: "Bourges",
    zipcode: "47521",
    phone: "0179129242",
    email: "rh@gie.fr",
    description:
        "Chuck Norris doesn't need the cloud to scale his applications, he uses his laptop.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Impasse de la Ferronnerie",
    name: "Remy et Remy",
    city: "Cholet",
    zipcode: "14896",
    phone: "+33 995603458",
    email: "rh@remy.fr",
    description: "No statement can catch the ChuckNorrisException.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Passage de la Bûcherie",
    name: "Charpentier SEM",
    city: "Clermont-Ferrand",
    zipcode: "88857",
    phone: "0585106609",
    email: "rh@charpentier.fr",
    description:
        "Chuck Norris doesn't need a java compiler, he goes straight to .war",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Place Saint-Denis",
    name: "Roussel et Roussel",
    city: "Amiens",
    zipcode: "14754",
    phone: "05 34 57 71 01",
    email: "rh@roussquare.fr",
    description: "Chuck Norris hosting is 101% uptime guaranteed.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Rue Montorgueil",
    name: "Blanchard et Blanchard SCOP",
    city: "Mulhouse",
    zipcode: "98521",
    phone: "+33 261239584",
    email: "rh@clementscop.fr",
    description:
        "All arrays Chuck Norris declares are of infinite size, because Chuck Norris knows no bounds.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Avenue Adolphe Mille",
    name: "Paul GIE",
    city: "Bourges",
    zipcode: "47521",
    phone: "0179129242",
    email: "rh@gie.fr",
    description:
        "Chuck Norris doesn't need the cloud to scale his applications, he uses his laptop.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Impasse de la Ferronnerie",
    name: "Remy et Remy",
    city: "Cholet",
    zipcode: "14896",
    phone: "+33 995603458",
    email: "rh@remy.fr",
    description: "No statement can catch the ChuckNorrisException.",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
  Client(
    adress: "Passage de la Bûcherie",
    name: "Charpentier SEM",
    city: "Clermont-Ferrand",
    zipcode: "88857",
    phone: "0585106609",
    email: "rh@charpentier.fr",
    description:
        "Chuck Norris doesn't need a java compiler, he goes straight to .war",
    logo: "assets/logo/logo_NFC_Circle.png",
  ),
];
