class Installation {
  final String? adress, city, zipcode, image;

  Installation({this.adress, this.city, this.image, this.zipcode});
}

List installationList = [
  Installation(
    adress: "60 Avenue de Maurin",
    city: "Montpellier",
    image: "assets/icons/ffffff.png",
    zipcode: "34000",
  ),
  Installation(
    adress: "565 Mr Charles",
    city: "Dijon",
    image: "assets/icons/ffffff.png",
    zipcode: "55687",
  ),
  Installation(
    adress: "32 Rue du Parpaing",
    city: "La Planche",
    image: "assets/icons/ffffff.png",
    zipcode: "99999",
  ),
  Installation(
    adress: "69 Silicone Valley",
    city: "La Street",
    image: "assets/icons/ffffff.png",
    zipcode: "35101",
  ),
  Installation(
    adress: "77 Maria Street",
    city: "District de Shiganshian",
    image: "assets/icons/ffffff.png",
    zipcode: "42584",
  ),
  Installation(
    adress: "3 Rue de Kaïo",
    city: "Z City",
    image: "assets/icons/ffffff.png",
    zipcode: "50152",
  ),
  Installation(
    adress: "54 Place des Sourires",
    city: "Bisounours Land",
    image: "assets/icons/ffffff.png",
    zipcode: "20202",
  ),
  Installation(
    adress: "6 Rue du Truc",
    city: "MachinVille",
    image: "assets/icons/ffffff.png",
    zipcode: "42424",
  ),
  Installation(
    adress: "12 Jean alpin",
    city: "La Fosse",
    image: "assets/icons/ffffff.png",
    zipcode: "45879",
  ),
  Installation(
    adress: "69 Ronins",
    city: "Pathé Gaumont",
    image: "assets/icons/ffffff.png",
    zipcode: "23748",
  ),
  Installation(
    adress: "60 Avenue de Maurin",
    city: "Montpellier",
    image: "assets/icons/ffffff.png",
    zipcode: "34000",
  ),
  Installation(
    adress: "565 Mr Charles",
    city: "Dijon",
    image: "assets/icons/ffffff.png",
    zipcode: "55687",
  ),
  Installation(
    adress: "32 Rue du Parpaing",
    city: "La Planche",
    image: "assets/icons/ffffff.png",
    zipcode: "99999",
  ),
  Installation(
    adress: "69 Silicone Valley",
    city: "La Street",
    image: "assets/icons/ffffff.png",
    zipcode: "35101",
  ),
  Installation(
    adress: "77 Maria Street",
    city: "District de Shiganshian",
    image: "assets/icons/ffffff.png",
    zipcode: "42584",
  ),
  Installation(
    adress: "3 Rue de Kaïo",
    city: "Z City",
    image: "assets/icons/ffffff.png",
    zipcode: "50152",
  ),
  Installation(
    adress: "54 Place des Sourires",
    city: "Bisounours Land",
    image: "assets/icons/ffffff.png",
    zipcode: "20202",
  ),
  Installation(
    adress: "6 Rue du Truc",
    city: "MachinVille",
    image: "assets/icons/ffffff.png",
    zipcode: "42424",
  ),
  Installation(
    adress: "12 Jean alpin",
    city: "La Fosse",
    image: "assets/icons/ffffff.png",
    zipcode: "45879",
  ),
  Installation(
    adress: "69 Ronins",
    city: "Pathé Gaumont",
    image: "assets/icons/ffffff.png",
    zipcode: "23748",
  ),
  Installation(
    adress: "60 Avenue de Maurin",
    city: "Montpellier",
    image: "assets/icons/ffffff.png",
    zipcode: "34000",
  ),
  Installation(
    adress: "565 Mr Charles",
    city: "Dijon",
    image: "assets/icons/ffffff.png",
    zipcode: "55687",
  ),
  Installation(
    adress: "32 Rue du Parpaing",
    city: "La Planche",
    image: "assets/icons/ffffff.png",
    zipcode: "99999",
  ),
  Installation(
    adress: "69 Silicone Valley",
    city: "La Street",
    image: "assets/icons/ffffff.png",
    zipcode: "35101",
  ),
  Installation(
    adress: "77 Maria Street",
    city: "District de Shiganshian",
    image: "assets/icons/ffffff.png",
    zipcode: "42584",
  ),
  Installation(
    adress: "3 Rue de Kaïo",
    city: "Z City",
    image: "assets/icons/ffffff.png",
    zipcode: "50152",
  ),
  Installation(
    adress: "54 Place des Sourires",
    city: "Bisounours Land",
    image: "assets/icons/ffffff.png",
    zipcode: "20202",
  ),
  Installation(
    adress: "6 Rue du Truc",
    city: "MachinVille",
    image: "assets/icons/ffffff.png",
    zipcode: "42424",
  ),
  Installation(
    adress: "12 Jean alpin",
    city: "La Fosse",
    image: "assets/icons/ffffff.png",
    zipcode: "45879",
  ),
  Installation(
    adress: "69 Ronins",
    city: "Pathé Gaumont",
    image: "assets/icons/ffffff.png",
    zipcode: "23748",
  ),
  Installation(
    adress: "60 Avenue de Maurin",
    city: "Montpellier",
    image: "assets/icons/ffffff.png",
    zipcode: "34000",
  ),
  Installation(
    adress: "565 Mr Charles",
    city: "Dijon",
    image: "assets/icons/ffffff.png",
    zipcode: "55687",
  ),
  Installation(
    adress: "32 Rue du Parpaing",
    city: "La Planche",
    image: "assets/icons/ffffff.png",
    zipcode: "99999",
  ),
  Installation(
    adress: "69 Silicone Valley",
    city: "La Street",
    image: "assets/icons/ffffff.png",
    zipcode: "35101",
  ),
  Installation(
    adress: "77 Maria Street",
    city: "District de Shiganshian",
    image: "assets/icons/ffffff.png",
    zipcode: "42584",
  ),
  Installation(
    adress: "3 Rue de Kaïo",
    city: "Z City",
    image: "assets/icons/ffffff.png",
    zipcode: "50152",
  ),
  Installation(
    adress: "54 Place des Sourires",
    city: "Bisounours Land",
    image: "assets/icons/ffffff.png",
    zipcode: "20202",
  ),
  Installation(
    adress: "6 Rue du Truc",
    city: "MachinVille",
    image: "assets/icons/ffffff.png",
    zipcode: "42424",
  ),
  Installation(
    adress: "12 Jean alpin",
    city: "La Fosse",
    image: "assets/icons/ffffff.png",
    zipcode: "45879",
  ),
  Installation(
    adress: "69 Ronins",
    city: "Pathé Gaumont",
    image: "assets/icons/ffffff.png",
    zipcode: "23748",
  ),
  Installation(
    adress: "60 Avenue de Maurin",
    city: "Montpellier",
    image: "assets/icons/ffffff.png",
    zipcode: "34000",
  ),
  Installation(
    adress: "565 Mr Charles",
    city: "Dijon",
    image: "assets/icons/ffffff.png",
    zipcode: "55687",
  ),
  Installation(
    adress: "32 Rue du Parpaing",
    city: "La Planche",
    image: "assets/icons/ffffff.png",
    zipcode: "99999",
  ),
  Installation(
    adress: "69 Silicone Valley",
    city: "La Street",
    image: "assets/icons/ffffff.png",
    zipcode: "35101",
  ),
  Installation(
    adress: "77 Maria Street",
    city: "District de Shiganshian",
    image: "assets/icons/ffffff.png",
    zipcode: "42584",
  ),
  Installation(
    adress: "3 Rue de Kaïo",
    city: "Z City",
    image: "assets/icons/ffffff.png",
    zipcode: "50152",
  ),
  Installation(
    adress: "54 Place des Sourires",
    city: "Bisounours Land",
    image: "assets/icons/ffffff.png",
    zipcode: "20202",
  ),
  Installation(
    adress: "6 Rue du Truc",
    city: "MachinVille",
    image: "assets/icons/ffffff.png",
    zipcode: "42424",
  ),
  Installation(
    adress: "12 Jean alpin",
    city: "La Fosse",
    image: "assets/icons/ffffff.png",
    zipcode: "45879",
  ),
  Installation(
    adress: "69 Ronins",
    city: "Pathé Gaumont",
    image: "assets/icons/ffffff.png",
    zipcode: "23748",
  ),
];
